/*
 * OptionsJFrame.java
 */
import java.awt.*;


public class DlgOptions extends javax.swing.JDialog
{
  private Dem m_dem;
  private String m_areaName;
  private String m_areaNames[];
  private String m_planeName;
  private String m_planeNames[];
  private MainViewJPanel m_mainView;

    /** Creates new form OptionsJFrame */
    public DlgOptions(Dem dem, MainViewJPanel mainView)
    {
        super(MainFrame.m_this, false);

        m_dem = dem;
        m_mainView = mainView;
        m_areaName = DemFactory.getAreaName();
        m_areaNames = DemFactory.getAreaNames();
        m_planeName = ProgramConfig.getPlaneName().substring(0, ProgramConfig.getPlaneName().length() - 4);
        m_planeNames = PlaneFactory.getPlaneNames();

        initComponents();
        setBounds(200, 200, 610, 500);
        
        allowWireframe.setSelected(ProgramConfig.isAllowWireframe());
        fpsJTextField.setText("" + ProgramConfig.getFramesPerSecond());

        setAreaNames(m_areaNames, m_areaName);
        setPlaneNames(m_planeNames, m_planeName);
        //planeNameJTextField.setText(ProgramConfig.getPlaneName());
        //planeNameJTextField.setEditable(false);
        
        rollFactorJTextField.setText("" + ProgramConfig.getRollFactor());
        yawFactorJTextField.setText("" + ProgramConfig.getYawFactor());
        pitchFactorJTextField.setText("" + ProgramConfig.getPitchFactor());
        speedFactorJTextField.setText("" + ProgramConfig.getSpeedFactor());
    }

    public void setAreaNames(String[] areaNames, String areaName)
    {
        int selectedIndex = 0;
        for(int i=0; i < areaNames.length ;i++) {
          areaNamesJComboBox.insertItemAt(areaNames[i], i);
          if(areaNames[i].equals(areaName)) {
              selectedIndex = i;
          }
        }
        areaNamesJComboBox.setSelectedIndex(selectedIndex);
    }
    
    public void setPlaneNames(String[] planeNames, String planeName)
    {
        int selectedIndex = 0;
        for(int i=0; i < planeNames.length ;i++) {
          planeNamesJComboBox.insertItemAt(planeNames[i], i);
          if(planeNames[i].equals(planeName)) {	
              selectedIndex = i;
          }
        }
        planeNamesJComboBox.setSelectedIndex(selectedIndex);
    }
      
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        okJButton = new javax.swing.JButton();
        allowWireframe = new javax.swing.JCheckBox();
        areaNamesJComboBox = new javax.swing.JComboBox();
        planeNamesJComboBox = new javax.swing.JComboBox();
        cancelJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rollFactorJTextField = new javax.swing.JTextField();
        yawFactorJTextField = new javax.swing.JTextField();
        pitchFactorJTextField = new javax.swing.JTextField();
        speedFactorJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fpsJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        planeNameJTextField = new javax.swing.JTextField();
        helpJButton = new javax.swing.JButton();
        
        getContentPane().setLayout(null);
        
        setTitle("whiskeyDem Options");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(okJButton);
        okJButton.setBounds(490, 40, 80, 27);
        
        allowWireframe.setText("Allow Wireframe");
        getContentPane().add(allowWireframe);
        allowWireframe.setBounds(60, 60, 120, 25);
        
        areaNamesJComboBox.setMaximumRowCount(20);
        getContentPane().add(areaNamesJComboBox);
        areaNamesJComboBox.setBounds(170, 330, 260, 26);
        
        planeNamesJComboBox.setMaximumRowCount(20);
        getContentPane().add(planeNamesJComboBox);
        planeNamesJComboBox.setBounds(170, 380, 260, 21);
        
        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(cancelJButton);
        cancelJButton.setBounds(490, 90, 80, 27);
        
        jLabel1.setText("Area (DEM) name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 330, 110, 30);
        
        jLabel2.setText("Flight Controls Sensitivity:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 360, 17);
        
        jLabel3.setText("Roll:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 210, 50, 20);
        
        jLabel4.setText("Yaw:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 250, 50, 20);
        
        jLabel5.setText("Pitch:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 210, 50, 20);
        
        jLabel6.setText("Speed:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 250, 50, 20);
        
        getContentPane().add(rollFactorJTextField);
        rollFactorJTextField.setBounds(110, 210, 100, 21);
        
        getContentPane().add(yawFactorJTextField);
        yawFactorJTextField.setBounds(110, 250, 100, 21);
        
        getContentPane().add(pitchFactorJTextField);
        pitchFactorJTextField.setBounds(330, 210, 100, 21);
        
        getContentPane().add(speedFactorJTextField);
        speedFactorJTextField.setBounds(330, 250, 100, 21);
        
        jLabel7.setText("Rendering:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 30, 120, 17);
        
        jLabel8.setText("Objects:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 300, 100, 17);
        
        jLabel9.setText("Frames Per Second:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 60, 120, 20);
        
        getContentPane().add(fpsJTextField);
        fpsJTextField.setBounds(350, 60, 70, 21);
        
        jLabel10.setText("Plane Name:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 380, 110, 20);
        
        //getContentPane().add(planeNameJTextField);
        //planeNameJTextField.setBounds(170, 380, 260, 21);
        
        helpJButton.setText("Help");
        helpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJButtonActionPerformed(evt);
            }
        });
        
        getContentPane().add(helpJButton);
        helpJButton.setBounds(490, 140, 80, 27);
        
        pack();
    }//GEN-END:initComponents

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        // Add your handling code here:
        cleanup();
    }//GEN-LAST:event_closeDialog

    private void helpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJButtonActionPerformed
        // Add your handling code here:
        new DlgHelp("dlgOptions").setVisible(true);
    }//GEN-LAST:event_helpJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // Add your handling code here:
        cleanup();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        // Add your handling code here:
        collectValues();
        cleanup();
    }//GEN-LAST:event_okJButtonActionPerformed

    private void cleanup()
    {
        setVisible(false);
        dispose();
    }

    private void collectValues() 
    {
      boolean bAllowWireframe = allowWireframe.isSelected();
      ProgramConfig.setAllowWireframe(bAllowWireframe);
      m_dem.setAllowWireframe(bAllowWireframe);
      
      int in = planeNamesJComboBox.getSelectedIndex();
      System.out.println("Plane name changed to " + m_planeNames[in]);
      ProgramConfig.setPlaneName(m_planeNames[in]);
            
     int fps = ProgramConfig.getFramesPerSecond();
      try {
          fps = Integer.parseInt(fpsJTextField.getText());
          ProgramConfig.setFramesPerSecond(fps);
          m_mainView.setFramesPerSecond();
      } catch (Exception e) {}

      if(m_mainView != null) {
          int index = areaNamesJComboBox.getSelectedIndex();
          //System.out.println("collectValues()    selected item=" + index);
          if(!m_areaNames[index].equals(m_areaName)) {
              System.out.println("dem name changed to " + m_areaNames[index]);
              m_mainView.anotherDem(index);
          }
      }
      
      double rollFactor = ProgramConfig.getRollFactor();
      try { rollFactor = Double.parseDouble(rollFactorJTextField.getText());
            ProgramConfig.setRollFactor(rollFactor); } catch (Exception e) {}

      double yawFactor = ProgramConfig.getYawFactor();
      try { yawFactor = Double.parseDouble(yawFactorJTextField.getText());
            ProgramConfig.setYawFactor(yawFactor);  } catch (Exception e) {}

      double pitchFactor = ProgramConfig.getPitchFactor();
      try { pitchFactor = Double.parseDouble(pitchFactorJTextField.getText());
            ProgramConfig.setPitchFactor(pitchFactor);  } catch (Exception e) {}

      double speedFactor = ProgramConfig.getSpeedFactor();
      try { speedFactor = Double.parseDouble(speedFactorJTextField.getText());
            ProgramConfig.setSpeedFactor(speedFactor);  } catch (Exception e) {}

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okJButton;
    private javax.swing.JCheckBox allowWireframe;
    private javax.swing.JComboBox areaNamesJComboBox;
    private javax.swing.JComboBox planeNamesJComboBox;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField rollFactorJTextField;
    private javax.swing.JTextField yawFactorJTextField;
    private javax.swing.JTextField pitchFactorJTextField;
    private javax.swing.JTextField speedFactorJTextField;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField fpsJTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField planeNameJTextField;
    private javax.swing.JButton helpJButton;
    // End of variables declaration//GEN-END:variables

}
